### ISSUE TITLE
hashed file names

### ISSUE THREAD

**Issue by alexcroox** [rollup/rollup-plugin-svelte#61]
First time using rollup so excuse the ignorance. Is it possible to export bundle.js/.css with hashed names so the browser doesn't serve cached versions when I push to production? How would this work updating `public/index.html`

**Comment by MaxMilton** [comment]
For general support questions you're better off asking on sites like [stackoverflow.com](https://stackoverflow.com/questions/tagged/rollup). Github issues are for reporting bugs or feature requests etc.

About your question, please read the rollup docs:

- <https://rollupjs.org/guide/en/#outputentryfilenames>
- <https://rollupjs.org/guide/en/#outputchunkfilenames>
- <https://rollupjs.org/guide/en/#outputassetfilenames>

**Comment by alexcroox** [comment]
Thank you and apologies for wasting your time. I missed that in the advanced section of the docs.

**Comment by MaxMilton** [comment]
It's all good. I know what it's like when you encounter a problem and just want to resolve it quickly.

Hope you were able to set your project up correctly :)

**Comment by jeduden** [comment]
Please note this that these suggestions don't work for the css file. See https://github.com/sveltejs/template/issues/39#issuecomment-513516115

**Comment by crisward** [comment]
I realised this is a closed issue. But it was the first one that appeared when googling, so I thought I drop a solution here for anyone who finds it useful (including future me...)

I found that the css object passed to the css function holds a hashed filename the same as your entry file, including the hash, but with the css extension.

So the below would output `index-[hash].js` and `index-[hash].css`

```javascript
//excerpt of rollup.js

export default {
	input: 'src/index.js',
	preserveEntrySignatures: false,
	output: {
		sourcemap: true,
		format: 'es',
		name: 'app',
		dir: 'build',
		entryFileNames: '[name]-[hash].js'
	},
	plugins: [
		svelte({
			// enable run-time checks when not in production
			css: css => {
				css.write(css.filename);
			}
    })
  ]
};
```

Also because I'm loading my css into a webcomponent, I parse the css filename by inspecting the module filename and swapping `.js` for `.css`

```javascript
//index.js
let css_filename = import.meta.url.match(/[^\/]+\.js$/)[0].replace(/\.js$/,".css")
```

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta for more info on this.

**Comment by lukeed** [comment]
CSS files will be hashed by default starting with 7.0 – see #136 
This is because the `CssWriter` class will respect the underlying Rollup configuration.

**Comment by brgrz** [comment]
> CSS files will be hashed by default starting with 7.0 – see #136
> This is because the `CssWriter` class will respect the underlying Rollup configuration.

I am not seeing this in action. CSS doesn't get hashed even with Rollup configured to output hashed JS files.

Please provide details (Rollup config) on how this is supposed to work.
